spring.application.name=portal360

# URL de conexión (poner nombre de tu base de datos): 
spring.datasource.url=jdbc:postgresql://localhost:5432/portal360
# Usuario por defecto de Postgres
spring.datasource.username=postgres
# Contraseña que usas para entrar en pgAdmin
spring.datasource.password=1218

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect